### ISSUE TITLE
Please remove warnings

### ISSUE THREAD

**Issue by asad-appifytech** [RATTLESNAKE-VIPER/GLGroupChatPicView#3]
**I am getting following Xcode warnings**

- GLGroupChatPicView.m:62:
Values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead

- GLGroupChatPicView.m:84:
Values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead

- GLGroupChatPicView.m:93:
Values of type 'NSUInteger' should not be used as format arguments; add an explicit cast to 'unsigned long' instead

- GLGroupChatPicView.m:261:
Address of function 'UIGraphicsBeginImageContextWithOptions' will always evaluate to 'true'

- GLGroupChatPicView.m:266:
Code will never be executed

**Please** remove these warnings and update your Pod version number, so I can get the warning free Pod. :)

**Comment by asad-appifytech** [comment]
Any update on above?

**Comment by RATTLESNAKE-VIPER** [comment]
Hi Asad,

Can you please send the pull-request with the fixes for this warnings as I will not be able to continue with this project anymore due to other project commitments. Will review/merge the pull-request as soon as possible.

Thanks in advance.

**Comment by RATTLESNAKE-VIPER** [comment]
Merged pull request from https://github.com/RATTLESNAKE-VIPER/GLGroupChatPicView/pull/4
